In [ ]:
# # !/usr/scripts/env python3
# import numpy as np
import numpy as np
print('numpy version:', np.__version__)

# from numpy import random
# print()
# # generate random numbers from 0 to 1

# data = random.rand(10)
# print(data) 
# # generate random numbers from 0 to 10 with
# #  a normal distribution -1 to 1

# normal_distribution = random.randn(10)
# print(normal_distribution)

# normal_dist_matrix = random.randn(3, 2)

# print(normal_dist_matrix)

# # Define a list
# elements = ['a', 'b', 'c', 'd', 'e', 'f']

# # Choose a random value from the list
# random_sample = random.choice(elements)

# print(random_sample)

# print('Before Shuffle', elements)
# random.shuffle(elements)
# print('After Shuffle', elements) # shuffling elements of array for randomness


# # Define a list of dishes on the menu
# menu = [
#     "Spaghetti Carbonara",
#     "Chicken Alfredo",
#     "Margherita Pizza",
#     "Cheeseburger",
#     "Caesar Salad",
#     "Fish and Chips",
#     "Pad Thai",
#     "Sushi Platter",
#     "Vegetable Stir-Fry",
#     "Grilled Salmon"
# ]

# # Function to suggest a random dish
# def suggest_dish():
#     random_dish = random.choice(menu)
#     return random_dish

# # Main program
# print("Welcome to the Restaurant Menu Randomizer!")
# print("If you're undecided about what to order, let us help you decide.")

# while True:
#     user_input = input("Press enter to get a random dish suggestion (or type 'quit' to exit): ")

#     if user_input.lower() == 'quit':
#         print("Thank you for using the Restaurant Menu Randomizer. Enjoy your meal!")
#         break

#     suggested_dish = suggest_dish()
#     print("Randomly suggested dish:", suggested_dish)
 


numpy version: 2.5.3
Element:  4
Slice:  [2 3 4]
[1 2 3 4 5]
[2 3 4]
[3 6 9]
[0.5 1.  1.5]
[10 10 10]
Sum:  15
Avg:  3.0
Median:  3.0
Standard Deviation:  1.4142135623730951
Min:  1
Max:  5
