In [1]:
import numpy as np
print('numpy version:', np.__version__)

numpy version: 2.5.3


In [13]:
# single dimensional arrays (Vector)
oneD = np.array( [1, 2, 3])

print(oneD)

# Two dimensional array (Matrix) Grid. Cery to a table
twoD = np.array(
    [
        [1, 2, 3],
        [3, 4, 6],
        [7, 8, 9]
    ]
)

print(twoD)

# Three dimensional Array (Tensor). set of matrices
threeD = np.array(
    [
        [
            [1, 2],
            [3, 4]
        ],
        [
            [5, 6],
            [7, 8]
        ]
    ]
)

print(threeD)

[1 2 3]
[[1 2 3]
 [3 4 6]
 [7 8 9]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [24]:
one_to_100=np.arange(100)
print(one_to_100)
one_to_30=np.arange(1,30)
print(one_to_30)
ten_twenty=np.arange(10,20,2)
print(ten_twenty)
print (oneD)
print(oneD.shape)
print(oneD.size)
print(oneD.dtype)
print(oneD.ndim)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29]
[10 12 14 16 18]
[1 2 3]
(3,)
3
int64
1


In [ ]:
from numpy import random 
